language: java
language: node_js
node_js:
  - "0.11"

before_install: npm install -g grunt-cli
before_install: npm install -g bower

install: npm install

after_success:
- gradle jacocoReport coveralls