language: java
language: node_js
node_js:
  - "0.10"

before_install: npm install -g grunt-cli
before_install: npm install -g bower

before_script: ./gradlew setup

after_success:
- gradle jacocoReport coveralls